----- Usage  -----
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ETL_WH;
USE DATABASE SALES_ANALYSIS_DB;
USE SCHEMA SALES_ANALYSIS_DB_SCHEMA;
-- Load Location data
COPY INTO LOCATION
FROM
    @SALES_ANALYSIS_DB.SALES_ANALYSIS_DB_SCHEMA.SALES_STAGE/Location.csv FILE_FORMAT = (
        TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );
-- Load Customers data
    COPY INTO CUSTOMERS
FROM
    @SALES_ANALYSIS_DB.SALES_ANALYSIS_DB_SCHEMA.SALES_STAGE/Customers.csv FILE_FORMAT = (
        TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );
-- Load Product data
    COPY INTO Product
FROM
    @SALES_ANALYSIS_DB.SALES_ANALYSIS_DB_SCHEMA.SALES_STAGE/Product.csv FILE_FORMAT = (
        TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );
-- Load Orders data
    COPY INTO ORDERS
FROM
    @SALES_ANALYSIS_DB.SALES_ANALYSIS_DB_SCHEMA.SALES_STAGE/Orders.csv FILE_FORMAT = (
        TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );
-- Load Store data
    COPY INTO STORE
FROM
    @SALES_ANALYSIS_DB.SALES_ANALYSIS_DB_SCHEMA.SALES_STAGE/Store.csv FILE_FORMAT = (
        TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );
--select * from orders limit 10;